import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch design tokens (preserved exactly)
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#8f0e14",
        "on-surface-variant": "#59413e",
        "on-secondary-fixed": "#1b1d04",
        "tertiary": "#30471e",
        "primary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#b3cf99",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#0b2000",
        "on-primary-container": "#ffbeb8",
        "surface-tint": "#b22a29",
        "on-primary-fixed": "#410003",
        "outline": "#8d706d",
        "secondary-fixed-dim": "#c8c9a0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#bbd8a1",
        "primary": "#86040f",
        "tertiary-container": "#465f33",
        "on-error": "#ffffff",
        "secondary": "#5f613f",
        "surface-variant": "#e5e2e1",
        "on-background": "#1b1b1b",
        "primary-fixed-dim": "#ffb3ac",
        "surface-container-highest": "#e5e2e1",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-fixed-variant": "#364d23",
        "on-secondary-container": "#636543",
        "surface-container": "#f0eded",
        "tertiary-fixed": "#ceecb3",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "error": "#ba1a1a",
        "background": "#fcf9f8",
        "inverse-primary": "#ffb3ac",
        "on-surface": "#1b1b1b",
        "on-tertiary": "#ffffff",
        "primary-container": "#a82323",
        "surface": "#fcf9f8",
        "inverse-surface": "#313030",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#e1e2b8",
        "secondary-fixed": "#e4e5bb",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#474929",
        "outline-variant": "#e1bfbb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
